"""
4/1//2024
---

"""
# Tkitner
import tkinter as tk
from tkinter import ttk
from tkinter import filedialog as fd 
from tkinter_objects import *
# SQLite
import sqlite3
from TableObjects import *
# Encryption
from cryptography.fernet import Fernet
#
from Screens import *

class RecipeApp(FrameController):
    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        self.sqlite_connector = None
        self.title("Recipe Book")
        self.byte_key = b''
        self.logged_in = False
    
    def generate_byte_key(self):
        '''
        Creates and returns a randomly generated byte key.
        '''
        self.byte_key = Fernet.generate_key()
        return self.byte_key
    
    def reset_byte_key(self):
        '''
        Sets the byte key to empty.
        '''
        self.byte_key = b''
    
    def get_byte_key(self):
        '''
        returns the byte key but returns a value error if the byte key is b''
        '''
        if self.byte_key != b'':
            return self.byte_key
        else:
            raise ValueError("The byte key has not been initialized")
    
    def save_byte_key(self, file_path):
        '''
        saves the byte key to a text file at a given path
        '''
        key_file = open(file_path, 'w')
        key_file.write(self.byte_key.decode())
        key_file.close()
    
    def load_byte_key(self, file_path):
        '''
        loads the byte key from a text from a given path
        '''
        key_file = open(file_path, 'r')
        self.byte_key = key_file.read().encode()
        key_file.close()

    def get_fernet(self):
        '''
        returns a fernet object used for encryption and decryption
        '''
        try:
            return Fernet(self.get_byte_key())
        except:
            print("Something went wrong")
    
    # sqlite functions #
    def connect_to_file(self, path:str, create_mode = False):
        self.close_connection()
        self.sqlite_connector = SqliteConnecter(path)

        # Gets everything needed to create a new database
        tables = [
            FoodCategory.get_table_string(), 
            Recipe.get_table_string(), 
            Ingredient.get_table_string(),
            User.get_table_string()
            ]
        categories = [
            FoodCategory(-1, "Breakfast"), FoodCategory(-1, "Lunch"), FoodCategory(-1, "Dinner")
            ]

        # Runs each of the commands in the tables.
        for table_command in tables:
            self.sqlite_connector.c.execute(table_command)
        
        # creates the food categories
        if create_mode:
            for category in categories:
                self.sqlite_connector.c.execute(category.to_sqlite())
        
        self.sqlite_connector.conn.commit()
    

    def close_connection(self):
        if isinstance(self.sqlite_connector, sqlite3.Connection):
            self.sqlite_connector.c.close()
    

    def get_connector(self):
        if not self.sqlite_connector:
            raise ValueError("A connection has not been created")
        else:
            return self.sqlite_connector
    # sqlite functions #


root = RecipeApp(screenName= "Recipe Book")

root.add_frame_direct("start", StartScreen(root.frame_holder, root))
root.add_frame_direct("create database", InitDatabaseScreen(root.frame_holder, root))
root.add_frame_direct("load database", InitDatabaseScreen(root.frame_holder, root, False))
root.add_frame_direct("recipe index", RecipeIndex(root.frame_holder, root))
root.add_frame_direct("view recipe", ViewRecipe(root.frame_holder, root, True))
root.add_frame_direct("create recipe", ViewRecipe(root.frame_holder, root, False))
root.add_frame_direct("create admin", CreateAdmin(root.frame_holder, root))
root.add_frame_direct("login", Login(root.frame_holder, root))
root.add_frame_direct("main menu", MainMenu(root.frame_holder, root))


root.open_frame("start")
root.mainloop()

"""
Resources:

https://stackoverflow.com/questions/2395431/using-tkinter-in-python-to-edit-the-title-bar
How to add a title

https://docs.python.org/3/library/dialog.html
How to create a file dialog

https://www.geeksforgeeks.org/how-to-encrypt-and-decrypt-strings-in-python/
How to encrypt and decrypt

https://tkdocs.com/tutorial/widgets.html#checkbutton
How to use basic widgets

https://www.geeksforgeeks.org/combobox-widget-in-tkinter-python/
How to put values into a list

https://victoria.dev/blog/do-i-raise-or-return-errors-in-python/
How to raise an error

https://stackoverflow.com/questions/31732177/tkinter-tclerror-bad-file-type-using-askopenfilename
use lists [] not arrays ()

https://www.tutorialspoint.com/python/tk_listbox.htm
how to insert into a listbox

https://www.sqlitetutorial.net/sqlite-where/
How to use where

https://youtu.be/IkjAkTMHrUw?si=fVK7FpRhiCdlq_Ia
How to use the text widgit

https://stackoverflow.com/questions/43860088/deselecting-from-a-listbox-in-tkinter
How to deselect items in a list box
"""